# KV Cache Compression Benchmark Pipeline

This notebook allows you to automatically execute and compare multiple KV cache compression techniques across LongBench and RULER benchmarks.

### "Ours" vs "CommonKV"
In this repository, **"ours"** and **"commonkv"** refer to the exact same methodology (the paper's proposed cross-layer SVD sharing). The codebase uses the flag `commonkv` when patching LLama models and `ours` when patching Mistral models for historical reasons.

In [1]:
!git clone https://github.com/Seqaeon/CommonKV.git

Cloning into 'CommonKV'...
remote: Enumerating objects: 631, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 631 (delta 0), reused 0 (delta 0), pack-reused 626 (from 2)
Receiving objects: 100% (631/631), 621.64 KiB | 5.45 MiB/s, done.
Resolving deltas: 100% (409/409), done.

In [2]:
!git pull origin main

fatal: not a git repository (or any parent up to mount point /kaggle)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

In [3]:
import os
os.chdir("/kaggle/working/CommonKV")
print(os.getcwd())

/kaggle/working/CommonKV

In [4]:
import os
import sys
import subprocess
import time
import json
import torch
import pandas as pd
from IPython.display import display, HTML

# Add repo path
sys.path.append(os.path.abspath('.'))

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Using device: {device}')

Using device: cuda

In [5]:
from kaggle_secrets import UserSecretsClient
user_secrets = UserSecretsClient()
secret_value_0 = user_secrets.get_secret("HF_TOKEN")
import os
os.environ["HF_TOKEN"] = secret_value_0 #"your_hf_token_here"

## 1. Define Pipeline Configuration

In [6]:
# MODEL_PATH =  "/kaggle/input/models/metaresearch/llama-3.1/transformers/8b-instruct/2" #'meta-llama/Meta-Llama-3.1-8B-Instruct'

# MODEL_PATH = "Qwen/Qwen2.5-0.5B-Instruct" # 'meta-llama/Meta-Llama-3.1-8B-Instruct'
# MODEL_PATH = "mistralai/Mistral-7B-Instruct-v0.2"
# MODEL_PATH = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
MODEL_PATH = "meta-llama/Llama-3.2-3B-Instruct"
# DATASET = 'narrativeqa' # Example LongBench dataset. Options: qasper, multifieldqa_en, hotpotqa, etc.
DATASET = 'all' # Set to 'all' to evaluate multiple datasets via --max_datasets

# The list of all compression methods to evaluate
# Options: 'fullkv', 'commonkv' (llama), 'ours' (mistral), 'think', 'palu', 'minicache', 'snapkv', 'pyramidkv', 'h2o', 'my_custom_method'
METHODS_TO_TEST = ["apkvc", 'commonkv' ,'fullkv', 'think', 'palu', 'minicache']

# # CommonKV / Baseline Parameters
# RANK = 4096
# LAYER_STEP = 2
# MAX_CAPACITY_PROMPTS = 8950

In [7]:
# --- Recommended Research Configuration ---
# MODEL_PATH = "alpindale/Mistral-7B-v0.2-hf" 
MAX_CAPACITY_PROMPTS = 1024  # Standard budget for most papers
RANK = 64                    # 2x compression for Palu/SVD
LAYER_STEP = 1               # Apply to every layer for consistency

# APKVC Specifics (to match the 1024 budget above)
MAX_ANCHOR_INTERVAL = 16 
PREDICTOR = "linear"         # Use 'linear' for much higher accuracy

## 2. Execute Benchmark Pipeline
Because the repository relies on **monkeypatching** the HuggingFace `transformers` global namespace to inject the different KV caching techniques, loading multiple methods sequentially in the same Python process will cause collisions and crashes.

To safely and programatically run all of them, we execute the repo's evaluation scripts (`run_longbench.py` and `run_ruler.py`) in isolated subprocesses.

**Note**: To evaluate `my_custom_method` on these benchmarks, you will need to add your custom logic hooks inside `commonkv/monkeypatch.py` so the `run_longbench.py` script can pick it up!

In [8]:
!sed -i 's/from modeling_llama/from commonkv.modeling_llama/g' commonkv/monkeypatch.py
!sed -i 's/from modeling_mistral/from commonkv.modeling_mistral/g' commonkv/monkeypatch.py
!sed -i 's/from llama_model/from commonkv.llama_model/g' commonkv/monkeypatch.py
!sed -i 's/from mistral_model/from commonkv.mistral_model/g' commonkv/monkeypatch.py

In [9]:
# %%bash
# git clone https://github.com/Zefan-Cai/PyramidKV.git /tmp/PyramidKV
# # If the repo contains an inner pyramidkv folder, extract it. 
# # Otherwise, treat the entire repo as the pyramidkv module itself!
# if [ -d "/tmp/PyramidKV/pyramidkv" ]; then 
#     cp -r /tmp/PyramidKV/pyramidkv ./
# else 
#     cp -r /tmp/PyramidKV ./pyramidkv
# fi

In [10]:
%%bash
# 1. Force the exact transformers version (>=4.44) the authors wrote patches for 
#    before Hugging Face removed `SlidingWindowCache` in 4.45+
pip install "transformers==4.44.2"

# 2. Install flash-attention (Required by llama_model.py)
#    Note: Compiling this from source might take ~10-15 minutes on Kaggle!
# pip install flash-attn --no-build-isolation

# 3. Clone PyramidKV
git clone https://github.com/Zefan-Cai/PyramidKV.git /tmp/PyramidKV

# 4. Generate a dynamic setup.py for it! 
#    Because the authors didn't include one, we'll force Python to recognize 
#    the root scripts or inner folders natively as a named module.
cat << 'EOF' > /tmp/PyramidKV/setup.py
from setuptools import setup, find_packages
import os

# Grab all standalone python scripts in the repo to bundle as modules
modules = [f[:-3] for f in os.listdir('.') if f.endswith('.py') and f != 'setup.py']

setup(
    name="pyramidkv",
    version="0.1.0",
    packages=find_packages(),
    py_modules=modules
)
EOF

# 5. Install it as a native python package using our minted setup.py
pip install -e /tmp/PyramidKV

Collecting transformers==4.44.2
  Downloading transformers-4.44.2-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.3 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (3.24.3)
Collecting huggingface-hub<1.0,>=0.23.2 (from transformers==4.44.2)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (2.32.4)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (0.7.0)
Collecting tokenizers<0.20,>=0.19 (from transformers==4.44.2)
  Downloading tokenizers-0.19.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.44.2) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.44.2) (1.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.44.2) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.44.2) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.44.2) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.44.2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.44.2) (2026.1.4)
Downloading transformers-4.44.2-py3-none-any.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 72.9 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 29.7 MB/s eta 0:00:00
Downloading tokenizers-0.19.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 94.9 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, tokenizers, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.4.1
    Uninstalling huggingface_hub-1.4.1:
      Successfully uninstalled huggingface_hub-1.4.1
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed huggingface-hub-0.36.2 tokenizers-0.19.1 transformers-4.44.2
Obtaining file:///tmp/PyramidKV
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Installing collected packages: pyramidkv
  Running setup.py develop for pyramidkv
Successfully installed pyramidkv-0.1.0

Cloning into '/tmp/PyramidKV'...
Updating files: 100% (166/166), done.

In [11]:
from datasets import load_dataset, Dataset
context_length = 4096
ds = load_dataset("simonjegou/ruler", str(context_length) , split="test")
# print(ds[0])
# ds.to_json("ruler_16384.jsonl")
import os

os.makedirs(f"data/RULER/{context_length}", exist_ok=True)

for task_name in set(ds["task"]):
    subset = ds.filter(lambda ex: ex["task"] == task_name)
    out_path = f"data/RULER/{context_length}/{task_name}.jsonl"
    subset.to_json(out_path)
    print(f"Saved {task_name} → {out_path}")

README.md: 0.00B [00:00, ?B/s]

4096/test-00000-of-00001.parquet:   0%|          | 0.00/24.4M [00:00<?, ?B/s]

Generating test split:   0%|          | 0/6500 [00:00<?, ? examples/s]

Filter:   0%|          | 0/6500 [00:00<?, ? examples/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved niah_single_1 → data/RULER/4096/niah_single_1.jsonl

Filter:   0%|          | 0/6500 [00:00<?, ? examples/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved niah_single_3 → data/RULER/4096/niah_single_3.jsonl

Filter:   0%|          | 0/6500 [00:00<?, ? examples/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved niah_multikey_2 → data/RULER/4096/niah_multikey_2.jsonl

Filter:   0%|          | 0/6500 [00:00<?, ? examples/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved niah_multiquery → data/RULER/4096/niah_multiquery.jsonl

Filter:   0%|          | 0/6500 [00:00<?, ? examples/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved niah_multikey_1 → data/RULER/4096/niah_multikey_1.jsonl

Filter:   0%|          | 0/6500 [00:00<?, ? examples/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved niah_single_2 → data/RULER/4096/niah_single_2.jsonl

Filter:   0%|          | 0/6500 [00:00<?, ? examples/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved niah_multikey_3 → data/RULER/4096/niah_multikey_3.jsonl

Filter:   0%|          | 0/6500 [00:00<?, ? examples/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved niah_multivalue → data/RULER/4096/niah_multivalue.jsonl

Filter:   0%|          | 0/6500 [00:00<?, ? examples/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved vt → data/RULER/4096/vt.jsonl

Filter:   0%|          | 0/6500 [00:00<?, ? examples/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved qa_2 → data/RULER/4096/qa_2.jsonl

Filter:   0%|          | 0/6500 [00:00<?, ? examples/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved cwe → data/RULER/4096/cwe.jsonl

Filter:   0%|          | 0/6500 [00:00<?, ? examples/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved qa_1 → data/RULER/4096/qa_1.jsonl

Filter:   0%|          | 0/6500 [00:00<?, ? examples/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved fwe → data/RULER/4096/fwe.jsonl

In [12]:
from huggingface_hub import hf_hub_download
import zipfile


file_path = hf_hub_download(
    repo_id="zai-org/LongBench",
    filename="data.zip",
    repo_type="dataset"
)


# zip_path = file_path   # path returned by hf_hub_download
# extract_dir = "./data/LongBench"

import os, zipfile

zip_path = file_path
extract_dir = "./data/LongBench"   # target root directory

with zipfile.ZipFile(zip_path, "r") as z:
    for member in z.namelist():
        # Strip the leading "data/" from paths inside the zip
        if member.startswith("data/"):
            relative_path = member[len("data/"):]  # remove "data/"
        else:
            relative_path = member

        # Skip empty directory entries
        if not relative_path:
            continue

        target_path = os.path.join(extract_dir, relative_path)

        # Make sure subdirectories exist
        os.makedirs(os.path.dirname(target_path), exist_ok=True)

        # Extract file contents
        if not member.endswith("/"):  # skip directories
            with z.open(member) as source, open(target_path, "wb") as target:
                target.write(source.read())

data.zip:   0%|          | 0.00/114M [00:00<?, ?B/s]

In [13]:
APKVC_CALIB_PATH = "./artifacts/apkvc/tinyllama_codebooks.pt"
USE_APKVC_CALIB = True
apkvc_use_rope_aware_aq = 1
import os, subprocess
os.makedirs("./traces", exist_ok=True)
APKVC_TRACE_PATH = "./traces/lb_mix.pt"
# LongBench trace dump
cmd_lb = [
    "python3", "run_longbench.py",
    "--method", "apkvc",
    "--model_path", MODEL_PATH,
    "--attn_implementation", "sdpa",
    "--dataset", "hotpotqa",
    "--steps", "100",
    "--save_dir", "./tmp_trace_run_lb",
    "--apkvc_use_rope_aware_aq", str(apkvc_use_rope_aware_aq),   # disable
    "--apkvc_trace_output_path", str(APKVC_TRACE_PATH),
    "--apkvc_trace_max_samples", "400000",
    "--apkvc_trace_chunk_size", "0",
    "--enforce_uniform_prefill_cap", "1",
    "--eval_batch_size", "1",
    "--max_prefill_tokens_for_custom_methods", "7950"
]
subprocess.run(cmd_lb, check=True)
print("LongBench trace created: ./traces/lb_mix.pt")

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
Downloading shards: 100%|██████████| 2/2 [00:28<00:00, 14.19s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.18s/it]

Loading data...
Max Length is 12697
Finish loading model and tokenizer

  0%|          | 0/200 [00:00<?, ?it/s]2026-03-28 06:41:51.720785: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1774680112.141802     369 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1774680112.245185     369 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1774680113.190468     369 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774680113.190508     369 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774680113.190511     369 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774680113.190513     369 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/usr/local/lib/python3.12/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  0%|          | 1/200 [01:02<3:26:52, 62.38s/it]/usr/local/lib/python3.12/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  1%|          | 2/200 [01:19<1:57:14, 35.53s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  2%|▏         | 3/200 [01:36<1:29:05, 27.14s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  2%|▏         | 4/200 [01:53<1:15:45, 23.19s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  2%|▎         | 5/200 [02:11<1:08:49, 21.18s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  3%|▎         | 6/200 [02:28<1:04:47, 20.04s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  4%|▎         | 7/200 [02:46<1:02:12, 19.34s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  4%|▍         | 8/200 [02:56<52:29, 16.41s/it]  Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  4%|▍         | 9/200 [03:14<53:51, 16.92s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  5%|▌         | 10/200 [03:33<54:43, 17.28s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  6%|▌         | 11/200 [03:51<55:39, 17.67s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  6%|▌         | 12/200 [04:09<55:57, 17.86s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  6%|▋         | 13/200 [04:28<55:59, 17.96s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  7%|▋         | 14/200 [04:46<55:57, 18.05s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  8%|▊         | 15/200 [05:04<56:02, 18.18s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  8%|▊         | 16/200 [05:23<55:53, 18.23s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  8%|▊         | 17/200 [05:41<55:58, 18.35s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  9%|▉         | 18/200 [05:59<55:31, 18.31s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 10%|▉         | 19/200 [06:18<55:21, 18.35s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 10%|█         | 20/200 [06:36<55:13, 18.41s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 10%|█         | 21/200 [06:55<55:02, 18.45s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 11%|█         | 22/200 [07:13<54:31, 18.38s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 12%|█▏        | 23/200 [07:32<54:34, 18.50s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 12%|█▏        | 24/200 [07:50<53:47, 18.34s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 12%|█▎        | 25/200 [08:08<53:32, 18.36s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 13%|█▎        | 26/200 [08:27<53:26, 18.43s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 14%|█▎        | 27/200 [08:45<52:46, 18.30s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 14%|█▍        | 28/200 [09:03<52:22, 18.27s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 14%|█▍        | 29/200 [09:17<48:14, 16.93s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 15%|█▌        | 30/200 [09:36<49:28, 17.46s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 16%|█▌        | 31/200 [09:54<50:10, 17.81s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 16%|█▌        | 32/200 [10:12<50:04, 17.89s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 16%|█▋        | 33/200 [10:31<50:02, 17.98s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 17%|█▋        | 34/200 [10:49<50:15, 18.17s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 18%|█▊        | 35/200 [11:08<50:12, 18.26s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 18%|█▊        | 36/200 [11:26<49:52, 18.25s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 18%|█▊        | 37/200 [11:44<49:46, 18.32s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 19%|█▉        | 38/200 [12:03<49:24, 18.30s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 20%|█▉        | 39/200 [12:21<49:10, 18.32s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 20%|██        | 40/200 [12:39<48:47, 18.30s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 20%|██        | 41/200 [12:58<48:37, 18.35s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 21%|██        | 42/200 [13:16<48:18, 18.34s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 22%|██▏       | 43/200 [13:34<48:00, 18.35s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 22%|██▏       | 44/200 [13:53<47:51, 18.40s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 22%|██▎       | 45/200 [14:11<47:24, 18.35s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 23%|██▎       | 46/200 [14:29<46:58, 18.30s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 24%|██▎       | 47/200 [14:49<47:22, 18.58s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 24%|██▍       | 48/200 [15:07<46:51, 18.49s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 24%|██▍       | 49/200 [15:25<46:25, 18.45s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 25%|██▌       | 50/200 [15:43<45:53, 18.36s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 26%|██▌       | 51/200 [16:02<45:36, 18.37s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 26%|██▌       | 52/200 [16:20<45:15, 18.35s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 26%|██▋       | 53/200 [16:38<44:50, 18.31s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 27%|██▋       | 54/200 [16:57<44:33, 18.31s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 28%|██▊       | 55/200 [17:15<44:05, 18.24s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 28%|██▊       | 56/200 [17:33<43:42, 18.21s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 28%|██▊       | 57/200 [17:51<43:26, 18.23s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 29%|██▉       | 58/200 [18:09<43:05, 18.21s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 30%|██▉       | 59/200 [18:27<42:42, 18.17s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 30%|███       | 60/200 [18:46<42:31, 18.22s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 30%|███       | 61/200 [19:04<42:21, 18.28s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 31%|███       | 62/200 [19:22<41:55, 18.23s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 32%|███▏      | 63/200 [19:40<41:34, 18.21s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 32%|███▏      | 64/200 [19:59<41:19, 18.23s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 32%|███▎      | 65/200 [20:17<41:03, 18.25s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 33%|███▎      | 66/200 [20:35<40:47, 18.27s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 34%|███▎      | 67/200 [20:54<40:32, 18.29s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 34%|███▍      | 68/200 [21:12<40:22, 18.35s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 34%|███▍      | 69/200 [21:29<39:11, 17.95s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 35%|███▌      | 70/200 [21:47<39:09, 18.08s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 36%|███▌      | 71/200 [22:06<38:56, 18.12s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 36%|███▌      | 72/200 [22:24<38:50, 18.20s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 36%|███▋      | 73/200 [22:42<38:31, 18.20s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 37%|███▋      | 74/200 [23:00<38:15, 18.21s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 38%|███▊      | 75/200 [23:19<38:06, 18.29s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 38%|███▊      | 76/200 [23:37<37:52, 18.33s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 38%|███▊      | 77/200 [23:56<37:40, 18.38s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 39%|███▉      | 78/200 [24:14<37:25, 18.40s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 40%|███▉      | 79/200 [24:33<37:04, 18.38s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 40%|████      | 80/200 [24:51<36:43, 18.37s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 40%|████      | 81/200 [25:09<36:24, 18.36s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 41%|████      | 82/200 [25:28<36:19, 18.47s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 42%|████▏     | 83/200 [25:46<35:59, 18.46s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 42%|████▏     | 84/200 [26:05<35:48, 18.52s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 42%|████▎     | 85/200 [26:24<35:31, 18.53s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 43%|████▎     | 86/200 [26:42<35:05, 18.47s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 44%|████▎     | 87/200 [27:01<34:50, 18.50s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 44%|████▍     | 88/200 [27:19<34:36, 18.54s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 44%|████▍     | 89/200 [27:38<34:18, 18.55s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 45%|████▌     | 90/200 [27:56<33:53, 18.48s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 46%|████▌     | 91/200 [28:15<33:36, 18.50s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 46%|████▌     | 92/200 [28:33<33:15, 18.47s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 46%|████▋     | 93/200 [28:51<32:52, 18.44s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 47%|████▋     | 94/200 [29:10<32:41, 18.51s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 48%|████▊     | 95/200 [29:29<32:23, 18.51s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 48%|████▊     | 96/200 [29:47<32:10, 18.56s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 48%|████▊     | 97/200 [30:06<31:50, 18.55s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 49%|████▉     | 98/200 [30:24<31:35, 18.59s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 50%|████▉     | 99/200 [30:42<30:45, 18.28s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 50%|█████     | 100/200 [31:00<31:00, 18.61s/it]

[APKVC] dumped trace residuals -> ./traces/lb_mix.pt
LongBench trace created: ./traces/lb_mix.pt

In [14]:
import os, subprocess
os.makedirs("./artifacts/apkvc", exist_ok=True)

trace_paths = [
    "./traces/lb_mix.pt",
    # "./traces/ruler_16k.pt",
]
for p in trace_paths:
    print(p, "exists?", os.path.exists(p))
calib_cmd = [
    "python3", "scripts/calibrate_apkvc_codebooks.py",
    "--trace_paths", "./traces/lb_mix.pt",
    "--output_path", APKVC_CALIB_PATH,
    "--K_num_codebooks", "4",
    "--V_num_codebooks", "2",
    "--codebook_size", "256",
    "--max_samples", "400000",
    "--chunk_size", "2048",
    "--device", "cuda",
]
print("Running:", " ".join(calib_cmd))
subprocess.run(calib_cmd, check=True)
print("Saved:", APKVC_CALIB_PATH)

./traces/lb_mix.pt exists? True
Running: python3 scripts/calibrate_apkvc_codebooks.py --trace_paths ./traces/lb_mix.pt --output_path ./artifacts/apkvc/tinyllama_codebooks.pt --K_num_codebooks 4 --V_num_codebooks 2 --codebook_size 256 --max_samples 400000 --chunk_size 2048 --device cuda
Saved calibrated codebooks -> ./artifacts/apkvc/tinyllama_codebooks.pt
Saved: ./artifacts/apkvc/tinyllama_codebooks.pt

In [15]:
# %%bash
# python3 scripts/calibrate_apkvc_codebooks.py \
#   --trace_paths ./traces/lb_mix.pt \
#   --output_path ./artifacts/apkvc/tinyllama_codebooks.pt \
#   --K_num_codebooks 4 \
#   --V_num_codebooks 2 \
#   --codebook_size 64 \
#   --max_samples 400000 \
#   --chunk_size 2048

In [16]:
# import torch
# p = "./artifacts/apkvc/tinyllama_codebooks.pt"
# obj = torch.load(p, map_location="cpu")
# print(type(obj))
# print(obj.keys() if isinstance(obj, dict) else "not dict")

In [17]:
longbench_results_dir = "./results_long_bench"
METHODS_TO_TEST = ["apkvc", "fullkv"]

os.makedirs(longbench_results_dir, exist_ok=True)

DUMP_APKVC_TRACES = False
USE_APKVC_CALIB = True
APKVC_CALIB_PATH = "./artifacts/apkvc/tinyllama_codebooks.pt"
APKVC_TRACE_PATH = "./traces/lb_mix.pt"

for method in METHODS_TO_TEST:
    print(f"\n{'='*50}\nEvaluating Method: {method.upper()}\n{'='*50}")
    eval_method = method

    # cmd = [
    #     "python3", "run_longbench.py",
    #     "--method", eval_method,
    #     "--model_path", MODEL_PATH,
    #     "--dataset", DATASET,
    #     "--max_capacity_prompts", str(MAX_CAPACITY_PROMPTS),
    #     "--attn_implementation", "sdpa",
    #     "--rank", str(RANK),
    #     "--layer_step", str(LAYER_STEP),
    #     "--save_dir", longbench_results_dir,
    #     "--eval_batch_size", "1",
    #     "--max_datasets", "2",
    #     "--steps", "20",
    #     "--enforce_uniform_prefill_cap", "1",
    #     "--max_prefill_tokens_for_custom_methods", "32768",
    #     "--truncation_policy", "head_tail",
    # ]
    cmd = [
        "python3", "run_longbench.py",
        "--method", eval_method,
        "--model_path", MODEL_PATH,
        "--dataset", DATASET,
        "--max_capacity_prompts", str(MAX_CAPACITY_PROMPTS),
        "--attn_implementation", "sdpa",
        "--rank", str(RANK),
        "--layer_step", str(LAYER_STEP),
        "--max_anchor_interval", str(MAX_ANCHOR_INTERVAL),
        "--predictor_type", PREDICTOR,
        "--save_dir", longbench_results_dir,
        "--apkvc_use_rope_aware_aq", str(apkvc_use_rope_aware_aq),   # disable
        "--eval_batch_size", "1",
        "--max_datasets", "2",
        "--steps", "20",
        "--enforce_uniform_prefill_cap", "1",
        "--max_prefill_tokens_for_custom_methods", "7950",# "32768",
        "--truncation_policy", "head_tail",

    ]

    if eval_method.lower() in ["apkvc", "custom"]:
        cmd.extend([
            "--max_anchor_interval", str(MAX_ANCHOR_INTERVAL),
            "--predictor_type", PREDICTOR,
            "--apkvc_use_rope_aware_aq", str(apkvc_use_rope_aware_aq),
        ])

        if DUMP_APKVC_TRACES:
            cmd.extend([
                "--apkvc_trace_output_path", APKVC_TRACE_PATH,
                "--apkvc_trace_max_samples", "400000",
            ])

        if USE_APKVC_CALIB:
            cmd.extend(["--apkvc_calibration_path", APKVC_CALIB_PATH])

    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    for line in process.stdout:
        print(line, end="")
    process.wait()
    print(f"\nReturn code: {process.returncode}")

==================================================
Evaluating Method: APKVC
==================================================

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:01<00:01,  1.78s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.08s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.19s/it]
Working on max_capacity_prompts 1024 dataset narrativeqa - 1/2
Loading data...
Max Length is 36418
Finish loading model and tokenizer

  0%|          | 0/200 [00:00<?, ?it/s]2026-03-28 07:13:13.382570: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1774681993.401343     927 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1774681993.407155     927 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1774681993.424460     927 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774681993.424487     927 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774681993.424490     927 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774681993.424493     927 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/usr/local/lib/python3.12/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  0%|          | 1/200 [00:36<2:01:08, 36.52s/it]/usr/local/lib/python3.12/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 2/200 [01:01<1:38:43, 29.92s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 3/200 [01:18<1:18:36, 23.94s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 4/200 [01:43<1:19:25, 24.31s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▎         | 5/200 [02:08<1:19:56, 24.60s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 6/200 [02:26<1:12:23, 22.39s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▎         | 7/200 [02:51<1:14:46, 23.24s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 8/200 [03:16<1:16:08, 23.80s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 9/200 [03:37<1:12:31, 22.78s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  5%|▌         | 10/200 [04:02<1:14:16, 23.46s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  6%|▌         | 11/200 [04:19<1:08:02, 21.60s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  6%|▌         | 12/200 [04:44<1:11:01, 22.67s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  6%|▋         | 13/200 [05:09<1:12:51, 23.38s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  7%|▋         | 14/200 [05:34<1:13:57, 23.86s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  8%|▊         | 15/200 [05:59<1:14:33, 24.18s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  8%|▊         | 16/200 [06:24<1:15:02, 24.47s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  8%|▊         | 17/200 [06:49<1:15:06, 24.62s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  9%|▉         | 18/200 [07:07<1:08:07, 22.46s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

 10%|▉         | 19/200 [07:32<1:10:00, 23.21s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

 10%|█         | 20/200 [07:57<1:11:18, 23.77s/it]
 10%|█         | 20/200 [07:57<1:11:34, 23.86s/it]
[APKVC] Loaded calibrated codebooks from: ./artifacts/apkvc/tinyllama_codebooks.pt
Working on max_capacity_prompts 1024 dataset qasper - 2/2
Loading data...
Max Length is 14660
Finish loading model and tokenizer

  0%|          | 0/200 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  0%|          | 1/200 [00:24<1:21:16, 24.50s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 2/200 [00:46<1:15:04, 22.75s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 3/200 [01:11<1:18:02, 23.77s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 4/200 [01:30<1:12:40, 22.25s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▎         | 5/200 [01:55<1:15:23, 23.20s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 6/200 [02:20<1:16:56, 23.80s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▎         | 7/200 [02:45<1:17:48, 24.19s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 8/200 [03:10<1:18:14, 24.45s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 9/200 [03:32<1:15:37, 23.75s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  5%|▌         | 10/200 [03:58<1:16:30, 24.16s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  6%|▌         | 11/200 [04:23<1:16:55, 24.42s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  6%|▌         | 12/200 [04:44<1:13:21, 23.41s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  6%|▋         | 13/200 [05:05<1:11:07, 22.82s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  7%|▋         | 14/200 [05:28<1:11:02, 22.92s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  8%|▊         | 15/200 [05:53<1:12:32, 23.52s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  8%|▊         | 16/200 [06:18<1:13:27, 23.95s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  8%|▊         | 17/200 [06:43<1:13:58, 24.26s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  9%|▉         | 18/200 [07:08<1:14:06, 24.43s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

 10%|▉         | 19/200 [07:33<1:14:04, 24.56s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

 10%|█         | 20/200 [07:58<1:13:55, 24.64s/it]
 10%|█         | 20/200 [07:58<1:11:43, 23.91s/it]

Return code: 0

==================================================
Evaluating Method: FULLKV
==================================================

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:01<00:01,  1.58s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.00s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.09s/it]
Working on max_capacity_prompts 1024 dataset narrativeqa - 1/2
Loading data...
Max Length is 36418
Finish loading model and tokenizer

  0%|          | 0/200 [00:00<?, ?it/s]2026-03-28 07:29:17.628524: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1774682957.648156     956 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1774682957.654053     956 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1774682957.671237     956 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774682957.671262     956 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774682957.671265     956 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774682957.671267     956 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/usr/local/lib/python3.12/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  0%|          | 1/200 [00:27<1:29:48, 27.08s/it]/usr/local/lib/python3.12/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 2/200 [00:42<1:07:22, 20.42s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 3/200 [00:58<1:00:05, 18.30s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 4/200 [01:14<56:47, 17.38s/it]  Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▎         | 5/200 [01:30<54:38, 16.81s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 6/200 [01:46<53:20, 16.50s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▎         | 7/200 [02:01<51:56, 16.15s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 8/200 [02:17<51:05, 15.97s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 9/200 [02:32<50:16, 15.79s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  5%|▌         | 10/200 [02:48<49:40, 15.69s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  6%|▌         | 11/200 [03:06<51:43, 16.42s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  6%|▌         | 12/200 [03:21<50:39, 16.17s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  6%|▋         | 13/200 [03:37<49:38, 15.93s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  7%|▋         | 14/200 [03:52<48:56, 15.79s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  8%|▊         | 15/200 [04:08<48:29, 15.72s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  8%|▊         | 16/200 [04:23<48:13, 15.73s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  8%|▊         | 17/200 [04:40<48:31, 15.91s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  9%|▉         | 18/200 [04:58<50:09, 16.54s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

 10%|▉         | 19/200 [05:13<49:02, 16.26s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

 10%|█         | 20/200 [05:29<48:04, 16.03s/it]
 10%|█         | 20/200 [05:29<49:24, 16.47s/it]
Working on max_capacity_prompts 1024 dataset qasper - 2/2
Loading data...
Max Length is 14660
Finish loading model and tokenizer

  0%|          | 0/200 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  0%|          | 1/200 [00:17<56:43, 17.10s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 2/200 [00:31<50:55, 15.43s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 3/200 [00:48<53:18, 16.24s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 4/200 [01:08<57:54, 17.73s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▎         | 5/200 [01:27<59:15, 18.23s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 6/200 [01:43<55:44, 17.24s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▎         | 7/200 [01:58<53:38, 16.67s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 8/200 [02:14<53:01, 16.57s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 9/200 [02:28<50:12, 15.77s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  5%|▌         | 10/200 [02:48<54:04, 17.08s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  6%|▌         | 11/200 [03:06<54:03, 17.16s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  6%|▌         | 12/200 [03:18<48:39, 15.53s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  6%|▋         | 13/200 [03:30<45:40, 14.65s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  7%|▋         | 14/200 [03:49<49:43, 16.04s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  8%|▊         | 15/200 [04:05<48:57, 15.88s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  8%|▊         | 16/200 [04:21<48:48, 15.92s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  8%|▊         | 17/200 [04:48<58:21, 19.14s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  9%|▉         | 18/200 [05:04<55:32, 18.31s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

 10%|▉         | 19/200 [05:30<1:02:34, 20.74s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

 10%|█         | 20/200 [05:47<58:39, 19.55s/it]
 10%|█         | 20/200 [05:47<52:08, 17.38s/it]

Return code: 0

## 3. Compare Results
The `run_longbench.py` script dumps `.json` files containing the model's generated text predictions. 
The official LongBench metrics (like F1 score, Exact Match, etc.) require the `eval.py` script from the official THUDM/LongBench repository. 

However, we can look at the generations and lengths directly generated from our pipeline loop!

In [18]:
!pip install rouge
!pip install python-Levenshtein

Collecting rouge
  Downloading rouge-1.0.1-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from rouge) (1.17.0)
Downloading rouge-1.0.1-py3-none-any.whl (13 kB)
Installing collected packages: rouge
Successfully installed rouge-1.0.1
Collecting python-Levenshtein
  Downloading python_levenshtein-0.27.3-py3-none-any.whl.metadata (3.9 kB)
Collecting Levenshtein==0.27.3 (from python-Levenshtein)
  Downloading levenshtein-0.27.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting rapidfuzz<4.0.0,>=3.9.0 (from Levenshtein==0.27.3->python-Levenshtein)
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading python_levenshtein-0.27.3-py3-none-any.whl (9.5 kB)
Downloading levenshtein-0.27.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (153 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.3/153.3 kB 3.9 MB/s eta 0:00:00a 0:00:01
Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 44.3 MB/s eta 0:00:0000:0100:01
Installing collected packages: rapidfuzz, Levenshtein, python-Levenshtein
Successfully installed Levenshtein-0.27.3 python-Levenshtein-0.27.3 rapidfuzz-3.14.3

In [19]:
import os, subprocess, pandas as pd

# results_dir = "/kaggle/working/CommonKV/results_long_bench/Mistral-7B-Instruct-v0.2_64_1_v4"
results_dir = "/kaggle/working/CommonKV/results_long_bench/Llama-3.2-3B-Instruct_64_1_v4"
# results_dir = "/kaggle/working/CommonKV/results_long_bench/TinyLlama-1.1B-Chat-v1.0_64_1_v4"

eval_py = "/kaggle/working/CommonKV/eval.py"

# 1. Run the evaluation once for all discovered methods
subprocess.run(["python3", eval_py, "--results_dir", results_dir])

# 2. Load the unified results.csv that eval.py now generates automatically
csv_path = os.path.join(results_dir, "results.csv")
if os.path.exists(csv_path):
    # Melt the broad table into the [dataset, method, score] format you wanted
    df = pd.read_csv(csv_path)
    scores_df = df.melt(id_vars=["dataset"], var_name="method", value_name="score")
    
    # Filter out empty results (-1) or methods that weren't evaluates
    scores_df = scores_df[scores_df["score"] != -1]
    
    display(scores_df.sort_values(["dataset", "method"]))
else:
    print("Evaluation failed to generate results.csv")

/usr/local/lib/python3.12/dist-packages/jieba/__init__.py:44: SyntaxWarning: invalid escape sequence '\.'
  re_han_default = re.compile("([\u4E00-\u9FD5a-zA-Z0-9+#&\._%\-]+)", re.U)
/usr/local/lib/python3.12/dist-packages/jieba/__init__.py:46: SyntaxWarning: invalid escape sequence '\s'
  re_skip_default = re.compile("(\r\n|\s)", re.U)
/usr/local/lib/python3.12/dist-packages/jieba/finalseg/__init__.py:78: SyntaxWarning: invalid escape sequence '\.'
  re_skip = re.compile("([a-zA-Z0-9]+(?:\.\d+)?%?)")

Datasets to evaluate: ['narrativeqa', 'qasper']
Methods to evaluate: ['FullKV', 'apkvc']
dataset narrativeqa method FullKV scores {'narrativeqa': 20.56, 'compression_ratio': np.float64(1.0), 'latency': np.float64(15.567804999999998), 'tps': np.float64(0.52356)}
dataset narrativeqa method apkvc scores {'narrativeqa': 3.48, 'compression_ratio': np.float64(0.06800000000000002), 'latency': np.float64(22.942605000000004), 'tps': np.float64(4.429150000000001)}
dataset qasper method FullKV scores {'qasper': 34.48, 'compression_ratio': np.float64(1.0), 'latency': np.float64(16.98771), 'tps': np.float64(1.8191)}
dataset qasper method apkvc scores {'qasper': 5.08, 'compression_ratio': np.float64(0.06800000000000002), 'latency': np.float64(23.4538), 'tps': np.float64(5.43309)}

==================================================
      TIE TABLE (Win / Loss / Tie)
==================================================
                     FullKV       apkvc
FullKV                    -       0/0/0
apkvc                 0/0/0           -
==================================================

100%|██████████| 2/2 [00:00<00:00, 38.78it/s]

       dataset  method  score
0  narrativeqa  FullKV  20.56
2  narrativeqa   apkvc   3.48
1       qasper  FullKV  34.48
3       qasper   apkvc   5.08

In [20]:
import os, pandas as pd

# results_dir = "/kaggle/working/CommonKV/results_long_bench/TinyLlama-1.1B-Chat-v1.0_4096_2_v4"
jsonl_path = os.path.join(results_dir, "results_long.jsonl")

if os.path.exists(jsonl_path):
    # 1. Read the machine-readable long format directly
    df = pd.read_json(jsonl_path, lines=True)
    
    # 2. Filter out missing results (-1)
    df = df[df["score"] != -1]
    
    # 3. Sort and Display (Score and CR are now in separate columns)
    display(df.sort_values(["dataset", "method"]))
else:
    print("Evaluation failed to generate results_long.jsonl")

       dataset  method  score  compression_ratio  latency   tps
0  narrativeqa  FullKV  20.56              1.000  15.5678  0.52
1  narrativeqa   apkvc   3.48              0.068  22.9426  4.43
2       qasper  FullKV  34.48              1.000  16.9877  1.82
3       qasper   apkvc   5.08              0.068  23.4538  5.43

In [21]:
# RULER trace dump
APKVC_CALIB_PATH = "./artifacts/apkvc/tinyllama_codebooks02.pt"
USE_APKVC_CALIB = True

cmd_ruler = [
    "python3", "run_ruler.py",
    "--method", "apkvc",
    "--model_path", MODEL_PATH,
    "--dataset", "niah_single_1",
    "--context_lengths", "4096",
    "--attn_implementation", "sdpa",
    "--steps", "100",
    "--save_dir", "./tmp_trace_run_ruler",
    "--apkvc_trace_output_path", "./traces/ruler_16k.pt",
    "--apkvc_trace_max_samples", "400000",
    "--enforce_uniform_prefill_cap", "1",
    "--eval_batch_size", "1",
    "--max_prefill_tokens_for_custom_methods", "7950"

]
subprocess.run(cmd_ruler, check=True)
print("RULER trace created: ./traces/ruler_16k.pt")

Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.10s/it]

Working on max_capacity_prompts 512 dataset niah_single_1 - Context 4096
Loading data...
Max Length is 13802
Finish loading model and tokenizer

  0%|          | 0/500 [00:00<?, ?it/s]2026-03-28 07:40:53.359997: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1774683653.385336    1002 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1774683653.393323    1002 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1774683653.414194    1002 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774683653.414221    1002 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774683653.414224    1002 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774683653.414226    1002 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/usr/local/lib/python3.12/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  0%|          | 1/500 [00:30<4:13:12, 30.45s/it]/usr/local/lib/python3.12/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  0%|          | 2/500 [00:49<3:18:54, 23.96s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  1%|          | 3/500 [01:09<3:01:00, 21.85s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  1%|          | 4/500 [01:28<2:51:08, 20.70s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  1%|          | 5/500 [01:47<2:45:47, 20.10s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  1%|          | 6/500 [02:06<2:42:53, 19.78s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  1%|▏         | 7/500 [02:25<2:40:21, 19.52s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  2%|▏         | 8/500 [02:44<2:38:21, 19.31s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  2%|▏         | 9/500 [03:03<2:36:59, 19.18s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  2%|▏         | 10/500 [03:22<2:36:00, 19.10s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  2%|▏         | 11/500 [03:41<2:35:42, 19.10s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  2%|▏         | 12/500 [03:59<2:34:20, 18.98s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  3%|▎         | 13/500 [04:18<2:33:53, 18.96s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  3%|▎         | 14/500 [04:37<2:33:36, 18.96s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  3%|▎         | 15/500 [04:56<2:32:34, 18.88s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  3%|▎         | 16/500 [05:15<2:33:06, 18.98s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  3%|▎         | 17/500 [05:34<2:32:40, 18.97s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  4%|▎         | 18/500 [05:53<2:32:19, 18.96s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  4%|▍         | 19/500 [06:12<2:31:45, 18.93s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  4%|▍         | 20/500 [06:31<2:31:31, 18.94s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  4%|▍         | 21/500 [06:50<2:31:08, 18.93s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  4%|▍         | 22/500 [07:09<2:31:15, 18.99s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  5%|▍         | 23/500 [07:28<2:30:48, 18.97s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  5%|▍         | 24/500 [07:47<2:30:50, 19.01s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  5%|▌         | 25/500 [08:06<2:30:42, 19.04s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  5%|▌         | 26/500 [08:25<2:30:31, 19.05s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  5%|▌         | 27/500 [08:44<2:30:30, 19.09s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  6%|▌         | 28/500 [09:03<2:29:28, 19.00s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  6%|▌         | 29/500 [09:22<2:28:51, 18.96s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  6%|▌         | 30/500 [09:41<2:28:23, 18.94s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  6%|▌         | 31/500 [09:59<2:26:59, 18.81s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  6%|▋         | 32/500 [10:18<2:26:50, 18.83s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  7%|▋         | 33/500 [10:37<2:25:50, 18.74s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  7%|▋         | 34/500 [10:55<2:25:38, 18.75s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  7%|▋         | 35/500 [11:14<2:24:44, 18.68s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  7%|▋         | 36/500 [11:33<2:25:11, 18.77s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  7%|▋         | 37/500 [11:52<2:25:05, 18.80s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  8%|▊         | 38/500 [12:11<2:25:07, 18.85s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  8%|▊         | 39/500 [12:30<2:25:28, 18.93s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  8%|▊         | 40/500 [12:49<2:25:05, 18.93s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  8%|▊         | 41/500 [13:08<2:24:44, 18.92s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  8%|▊         | 42/500 [13:26<2:23:42, 18.83s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  9%|▊         | 43/500 [13:45<2:23:33, 18.85s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  9%|▉         | 44/500 [14:04<2:24:02, 18.95s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  9%|▉         | 45/500 [14:24<2:23:56, 18.98s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  9%|▉         | 46/500 [14:42<2:23:25, 18.95s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  9%|▉         | 47/500 [15:02<2:23:43, 19.04s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 10%|▉         | 48/500 [15:21<2:23:33, 19.06s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 10%|▉         | 49/500 [15:40<2:23:18, 19.07s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 10%|█         | 50/500 [15:59<2:23:09, 19.09s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 10%|█         | 51/500 [16:18<2:23:14, 19.14s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 10%|█         | 52/500 [16:37<2:22:17, 19.06s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 11%|█         | 53/500 [16:56<2:22:05, 19.07s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 11%|█         | 54/500 [17:15<2:21:47, 19.08s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 11%|█         | 55/500 [17:34<2:21:19, 19.06s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 11%|█         | 56/500 [17:53<2:20:27, 18.98s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 11%|█▏        | 57/500 [18:12<2:20:14, 19.00s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 12%|█▏        | 58/500 [18:31<2:19:49, 18.98s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 12%|█▏        | 59/500 [18:50<2:19:10, 18.93s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 12%|█▏        | 60/500 [19:09<2:19:17, 18.99s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 12%|█▏        | 61/500 [19:28<2:19:47, 19.10s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 12%|█▏        | 62/500 [19:48<2:19:32, 19.11s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 13%|█▎        | 63/500 [20:07<2:19:13, 19.12s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 13%|█▎        | 64/500 [20:26<2:18:54, 19.12s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 13%|█▎        | 65/500 [20:45<2:18:57, 19.17s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 13%|█▎        | 66/500 [21:04<2:18:39, 19.17s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 13%|█▎        | 67/500 [21:23<2:18:11, 19.15s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 14%|█▎        | 68/500 [21:42<2:17:44, 19.13s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 14%|█▍        | 69/500 [22:02<2:17:37, 19.16s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 14%|█▍        | 70/500 [22:21<2:17:39, 19.21s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 14%|█▍        | 71/500 [22:40<2:16:44, 19.12s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 14%|█▍        | 72/500 [22:59<2:16:33, 19.14s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 15%|█▍        | 73/500 [23:18<2:15:20, 19.02s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 15%|█▍        | 74/500 [23:37<2:16:03, 19.16s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 15%|█▌        | 75/500 [23:57<2:15:58, 19.20s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 15%|█▌        | 76/500 [24:16<2:15:33, 19.18s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 15%|█▌        | 77/500 [24:35<2:14:55, 19.14s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 16%|█▌        | 78/500 [24:54<2:14:57, 19.19s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 16%|█▌        | 79/500 [25:13<2:14:46, 19.21s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 16%|█▌        | 80/500 [25:32<2:13:52, 19.12s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 16%|█▌        | 81/500 [25:51<2:13:49, 19.16s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 16%|█▋        | 82/500 [26:11<2:13:21, 19.14s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 17%|█▋        | 83/500 [26:30<2:12:47, 19.11s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 17%|█▋        | 84/500 [26:49<2:12:42, 19.14s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 17%|█▋        | 85/500 [27:08<2:12:42, 19.19s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 17%|█▋        | 86/500 [27:27<2:12:24, 19.19s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 17%|█▋        | 87/500 [27:46<2:11:39, 19.13s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 18%|█▊        | 88/500 [28:05<2:11:24, 19.14s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 18%|█▊        | 89/500 [28:25<2:11:02, 19.13s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 18%|█▊        | 90/500 [28:44<2:10:49, 19.14s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 18%|█▊        | 91/500 [29:03<2:10:22, 19.13s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 18%|█▊        | 92/500 [29:22<2:09:57, 19.11s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 19%|█▊        | 93/500 [29:41<2:09:51, 19.14s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 19%|█▉        | 94/500 [30:01<2:10:03, 19.22s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 19%|█▉        | 95/500 [30:19<2:08:59, 19.11s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 19%|█▉        | 96/500 [30:39<2:09:09, 19.18s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 19%|█▉        | 97/500 [30:58<2:08:41, 19.16s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 20%|█▉        | 98/500 [31:17<2:07:56, 19.10s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 20%|█▉        | 99/500 [31:36<2:07:45, 19.12s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 20%|██        | 100/500 [31:55<2:07:42, 19.16s/it]

[APKVC] dumped trace residuals -> ./traces/ruler_16k.pt
RULER trace created: ./traces/ruler_16k.pt

In [22]:
import os, subprocess
os.makedirs("./artifacts/apkvc", exist_ok=True)

trace_paths = [
    "./traces/ruler_16k.pt",
    # "./traces/ruler_16k.pt",
]
for p in trace_paths:
    print(p, "exists?", os.path.exists(p))
calib_cmd = [
    "python3", "scripts/calibrate_apkvc_codebooks.py",
    "--trace_paths", "./traces/ruler_16k.pt",
    "--output_path", APKVC_CALIB_PATH,
    "--K_num_codebooks", "4",
    "--V_num_codebooks", "2",
    "--codebook_size", "256",
    "--max_samples", "400000",
    "--chunk_size", "2048",
    "--device", "cuda",
]
print("Running:", " ".join(calib_cmd))
subprocess.run(calib_cmd, check=True)
print("Saved:", APKVC_CALIB_PATH)

./traces/ruler_16k.pt exists? True
Running: python3 scripts/calibrate_apkvc_codebooks.py --trace_paths ./traces/ruler_16k.pt --output_path ./artifacts/apkvc/tinyllama_codebooks02.pt --K_num_codebooks 4 --V_num_codebooks 2 --codebook_size 256 --max_samples 400000 --chunk_size 2048 --device cuda
Saved calibrated codebooks -> ./artifacts/apkvc/tinyllama_codebooks02.pt
Saved: ./artifacts/apkvc/tinyllama_codebooks02.pt

In [23]:
ruler_results_dir = "./results_ruler"
METHODS_TO_TEST = ["apkvc", "fullkv"]
MAX_CAPACITY_PROMPTS = 1024
os.makedirs(ruler_results_dir, exist_ok=True)

DUMP_APKVC_TRACES = False
USE_APKVC_CALIB = True
APKVC_CALIB_PATH = "./artifacts/apkvc/tinyllama_codebooks02.pt"
APKVC_TRACE_PATH = "./traces/ruler_16k.pt"

for method in METHODS_TO_TEST:
    print(f"\n{'='*50}\nEvaluating Method: {method.upper()}\n{'='*50}")
    eval_method = method

    # cmd = [
    #     "python3", "run_longbench.py",
    #     "--method", eval_method,
    #     "--model_path", MODEL_PATH,
    #     "--dataset", DATASET,
    #     "--max_capacity_prompts", str(MAX_CAPACITY_PROMPTS),
    #     "--attn_implementation", "sdpa",
    #     "--rank", str(RANK),
    #     "--layer_step", str(LAYER_STEP),
    #     "--save_dir", longbench_results_dir,
    #     "--eval_batch_size", "1",
    #     "--max_datasets", "2",
    #     "--steps", "20",
    #     "--enforce_uniform_prefill_cap", "1",
    #     "--max_prefill_tokens_for_custom_methods", "32768",
    #     "--truncation_policy", "head_tail",
    # ]
    cmd = [
        "python3", "run_ruler.py",
        "--method", eval_method,
        "--model_path", MODEL_PATH,
        "--dataset", DATASET,
        "--max_capacity_prompts", str(MAX_CAPACITY_PROMPTS),
        "--attn_implementation", "sdpa",
        "--rank", str(RANK),
        "--layer_step", str(LAYER_STEP),
        "--max_anchor_interval", str(MAX_ANCHOR_INTERVAL),
        "--predictor_type", PREDICTOR,
        "--save_dir", ruler_results_dir,
        "--apkvc_use_rope_aware_aq", str(apkvc_use_rope_aware_aq),   # disable
        "--eval_batch_size", "1",
        "--context_lengths", "4096",
        "--max_datasets", "2",
        "--steps", "20",
        "--enforce_uniform_prefill_cap", "1",
        "--max_prefill_tokens_for_custom_methods", "7950",# "32768",
        "--truncation_policy", "head_tail",

    ]

    if eval_method.lower() in ["apkvc", "custom"]:
        cmd.extend([
            "--max_anchor_interval", str(MAX_ANCHOR_INTERVAL),
            "--predictor_type", PREDICTOR,
            "--apkvc_use_rope_aware_aq", str(apkvc_use_rope_aware_aq),
        ])

        if DUMP_APKVC_TRACES:
            cmd.extend([
                "--apkvc_trace_output_path", APKVC_TRACE_PATH,
                "--apkvc_trace_max_samples", "400000",
            ])

        if USE_APKVC_CALIB:
            cmd.extend(["--apkvc_calibration_path", APKVC_CALIB_PATH])

    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    for line in process.stdout:
        print(line, end="")
    process.wait()
    print(f"\nReturn code: {process.returncode}")

==================================================
Evaluating Method: APKVC
==================================================

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:01<00:01,  1.66s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.02s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.12s/it]
Working on max_capacity_prompts 1024 dataset niah_single_1 - 1/2 - Context 4096
Loading data...
Max Length is 13802
Finish loading model and tokenizer

  0%|          | 0/500 [00:00<?, ?it/s]2026-03-28 08:13:08.323370: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1774685588.348856    1039 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1774685588.357685    1039 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1774685588.379359    1039 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774685588.379401    1039 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774685588.379405    1039 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774685588.379409    1039 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/usr/local/lib/python3.12/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  0%|          | 1/500 [00:29<4:04:54, 29.45s/it]/usr/local/lib/python3.12/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  0%|          | 2/500 [00:48<3:11:42, 23.10s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 3/500 [01:06<2:53:28, 20.94s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 4/500 [01:24<2:44:10, 19.86s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 5/500 [01:42<2:39:06, 19.29s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 6/500 [02:01<2:36:20, 18.99s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|▏         | 7/500 [02:19<2:34:18, 18.78s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 8/500 [02:37<2:32:26, 18.59s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 9/500 [02:56<2:31:17, 18.49s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 10/500 [03:14<2:30:46, 18.46s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 11/500 [03:32<2:30:00, 18.41s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 12/500 [03:51<2:29:50, 18.42s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 13/500 [04:09<2:29:24, 18.41s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 14/500 [04:28<2:29:02, 18.40s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 15/500 [04:46<2:28:40, 18.39s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 16/500 [05:04<2:28:23, 18.40s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 17/500 [05:23<2:27:52, 18.37s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▎         | 18/500 [05:41<2:27:28, 18.36s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 19/500 [05:59<2:27:19, 18.38s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 20/500 [06:18<2:27:02, 18.38s/it]
  4%|▍         | 20/500 [06:18<2:31:18, 18.91s/it]
[APKVC] Loaded calibrated codebooks from: ./artifacts/apkvc/tinyllama_codebooks02.pt
Working on max_capacity_prompts 1024 dataset niah_single_2 - 2/2 - Context 4096
Loading data...
Max Length is 17776
Finish loading model and tokenizer

  0%|          | 0/500 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  0%|          | 1/500 [00:18<2:36:48, 18.86s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  0%|          | 2/500 [00:37<2:35:25, 18.73s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 3/500 [00:56<2:35:20, 18.75s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 4/500 [01:15<2:34:58, 18.75s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 5/500 [01:33<2:35:17, 18.82s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 6/500 [01:52<2:34:55, 18.82s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|▏         | 7/500 [02:11<2:34:19, 18.78s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 8/500 [02:30<2:33:45, 18.75s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 9/500 [02:48<2:33:11, 18.72s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 10/500 [03:07<2:33:08, 18.75s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 11/500 [03:26<2:32:52, 18.76s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 12/500 [03:45<2:32:31, 18.75s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 13/500 [04:04<2:32:26, 18.78s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 14/500 [04:22<2:32:07, 18.78s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 15/500 [04:41<2:31:31, 18.74s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 16/500 [05:00<2:31:17, 18.76s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 17/500 [05:18<2:30:50, 18.74s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▎         | 18/500 [05:37<2:30:18, 18.71s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 19/500 [05:56<2:30:08, 18.73s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 20/500 [06:15<2:29:59, 18.75s/it]
  4%|▍         | 20/500 [06:15<2:30:03, 18.76s/it]

Return code: 0

==================================================
Evaluating Method: FULLKV
==================================================

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:01<00:01,  1.66s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.04s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.13s/it]
Working on max_capacity_prompts 1024 dataset niah_single_1 - 1/2 - Context 4096
Loading data...
Max Length is 13802
Finish loading model and tokenizer

  0%|          | 0/500 [00:00<?, ?it/s]2026-03-28 08:25:51.022358: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1774686351.048651    1068 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1774686351.057300    1068 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1774686351.078827    1068 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774686351.078878    1068 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774686351.078882    1068 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774686351.078885    1068 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/usr/local/lib/python3.12/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  0%|          | 1/500 [00:25<3:31:24, 25.42s/it]/usr/local/lib/python3.12/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  0%|          | 2/500 [00:39<2:35:17, 18.71s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 3/500 [00:53<2:17:46, 16.63s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 4/500 [01:07<2:08:38, 15.56s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 5/500 [01:21<2:02:56, 14.90s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 6/500 [01:34<1:59:27, 14.51s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|▏         | 7/500 [01:48<1:57:12, 14.26s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 8/500 [02:02<1:55:51, 14.13s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 9/500 [02:16<1:54:53, 14.04s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 10/500 [02:30<1:53:59, 13.96s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 11/500 [02:43<1:53:06, 13.88s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 12/500 [03:02<2:04:48, 15.34s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 13/500 [03:16<2:01:04, 14.92s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 14/500 [03:30<1:57:58, 14.57s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 15/500 [03:44<1:55:44, 14.32s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 16/500 [03:57<1:54:21, 14.18s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 17/500 [04:11<1:53:19, 14.08s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▎         | 18/500 [04:25<1:52:26, 14.00s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 19/500 [04:39<1:51:51, 13.95s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 20/500 [04:58<2:03:03, 15.38s/it]
  4%|▍         | 20/500 [04:58<1:59:14, 14.91s/it]
Working on max_capacity_prompts 1024 dataset niah_single_2 - 2/2 - Context 4096
Loading data...
Max Length is 17776
Finish loading model and tokenizer

  0%|          | 0/500 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  0%|          | 1/500 [00:18<2:34:34, 18.59s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  0%|          | 2/500 [00:34<2:20:31, 16.93s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 3/500 [00:53<2:28:12, 17.89s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 4/500 [01:11<2:27:59, 17.90s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 5/500 [01:25<2:16:44, 16.57s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|          | 6/500 [01:44<2:23:23, 17.42s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  1%|▏         | 7/500 [02:03<2:27:42, 17.98s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 8/500 [02:22<2:30:19, 18.33s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 9/500 [02:41<2:31:41, 18.54s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 10/500 [02:55<2:20:20, 17.19s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 11/500 [03:11<2:15:11, 16.59s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  2%|▏         | 12/500 [03:25<2:08:57, 15.86s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 13/500 [03:44<2:16:35, 16.83s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 14/500 [04:03<2:20:46, 17.38s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 15/500 [04:22<2:24:31, 17.88s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 16/500 [04:41<2:27:08, 18.24s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  3%|▎         | 17/500 [05:00<2:29:01, 18.51s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▎         | 18/500 [05:19<2:29:58, 18.67s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 19/500 [05:38<2:30:37, 18.79s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

  4%|▍         | 20/500 [05:57<2:31:10, 18.90s/it]
  4%|▍         | 20/500 [05:57<2:23:02, 17.88s/it]

Return code: 0

In [24]:
import os, subprocess, pandas as pd

# results_dir = "/kaggle/working/CommonKV/results_long_bench/Mistral-7B-Instruct-v0.2_64_1_v4"
results_dir = "/kaggle/working/CommonKV/results_ruler/Llama-3.2-3B-Instruct_1024/4096"
# results_dir = "/kaggle/working/CommonKV/results_long_bench/TinyLlama-1.1B-Chat-v1.0_64_1_v4"

eval_py = "/kaggle/working/CommonKV/eval_ruler.py"

# 1. Run the evaluation once for all discovered methods
subprocess.run(["python3", eval_py, "--results_dir", results_dir])

# 2. Load the unified results.csv that eval.py now generates automatically
csv_path = os.path.join(results_dir, "results.csv")
if os.path.exists(csv_path):
    # Melt the broad table into the [dataset, method, score] format you wanted
    df = pd.read_csv(csv_path)
    scores_df = df.melt(id_vars=["dataset"], var_name="method", value_name="score")
    
    # Filter out empty results (-1) or methods that weren't evaluates
    scores_df = scores_df[scores_df["score"] != -1]
    
    display(scores_df.sort_values(["dataset", "method"]))
else:
    print("Evaluation failed to generate results.csv")

Datasets to evaluate: ['niah_single_1', 'niah_single_2']
Methods to evaluate: ['FullKV', 'apkvc']

[DONE] Evaluation complete. Summary saved to: /kaggle/working/CommonKV/results_ruler/Llama-3.2-3B-Instruct_1024/4096
- Wide scores: results.csv
- Wide ratios: compression_ratios.csv
- Long format: results_ruler.jsonl

100%|██████████| 2/2 [00:00<00:00, 155.86it/s]

         dataset  method  score
0  niah_single_1  FullKV  100.0
2  niah_single_1   apkvc   95.0
1  niah_single_2  FullKV  100.0
3  niah_single_2   apkvc   85.0

In [25]:
!python3 eval_ruler.py --results_dir /kaggle/working/CommonKV/results_ruler/Llama-3.2-3B-Instruct_1024/4096

Datasets to evaluate: ['niah_single_1', 'niah_single_2']
Methods to evaluate: ['FullKV', 'apkvc']
100%|████████████████████████████████████████████| 2/2 [00:00<00:00, 160.55it/s]

[DONE] Evaluation complete. Summary saved to: /kaggle/working/CommonKV/results_ruler/Llama-3.2-3B-Instruct_1024/4096
- Wide scores: results.csv
- Wide ratios: compression_ratios.csv
- Long format: results_ruler.jsonl

In [26]:
import os, pandas as pd

# results_dir = "/kaggle/working/CommonKV/results_long_bench/TinyLlama-1.1B-Chat-v1.0_4096_2_v4"
jsonl_path = os.path.join(results_dir, "results_ruler.jsonl")

if os.path.exists(jsonl_path):
    # 1. Read the machine-readable long format directly
    df = pd.read_json(jsonl_path, lines=True)
    
    # 2. Filter out missing results (-1)
    df = df[df["score"] != -1]
    
    # 3. Sort and Display (Score and CR are now in separate columns)
    display(df.sort_values(["dataset", "method"]))
else:
    print("Evaluation failed to generate results_rule.jsonl")

         dataset  method  score  compression_ratio  latency   tps
0  niah_single_1  FullKV    100              1.000  14.0604  0.68
1  niah_single_1   apkvc     95              0.068  18.0532  3.55
2  niah_single_2  FullKV    100              1.000  17.5045  2.70
3  niah_single_2   apkvc     85              0.068  18.3025  3.50

In [27]:
# import json
# a = [json.loads(x) for x in open("/kaggle/working/CommonKV/results_long_bench/Mistral-7B-Instruct-v0.2_4096_2_v4/narrativeqa/minicache.json")]
# b = [json.loads(x) for x in open("/kaggle/working/CommonKV/results_long_bench/Mistral-7B-Instruct-v0.2_4096_2_v4/narrativeqa/palu.json")]
# print(sum(x["pred"]==y["pred"] for x,y in zip(a,b)), "identical preds out of", len(a))

In [28]:
# !sh scripts/scripts_longBench/metrics.sh /kaggle/working/CommonKV/results_long_bench/Mistral-7B-Instruct-v0.2_4096_2_v4 /kaggle/working/CommonKV/eval.py

In [29]:
from transformers import AutoConfig, AutoModelForCausalLM
from commonkv.monkeypatch import replace_llama, replace_mistral

def inspect_method(method, model_path):
    m = method.lower()
    replace_llama(m); replace_mistral(m)
    cfg = AutoConfig.from_pretrained(model_path, use_cache=True)
    model = AutoModelForCausalLM.from_pretrained(model_path, config=cfg, torch_dtype="auto", device_map="auto")
    attn = model.model.layers[0].self_attn
    print(method, "attn_class=", attn.__class__.__name__,
          "window_size=", getattr(attn.config, "window_size", None),
          "max_capacity_prompt=", getattr(attn.config, "max_capacity_prompt", None))
    del model

inspect_method("FullKV", MODEL_PATH)
inspect_method("ThinK", MODEL_PATH)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

FullKV attn_class= LlamaSdpaAttention window_size= None max_capacity_prompt= None

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

ThinK attn_class= LlamaSdpaAttention window_size= None max_capacity_prompt= None

In [30]:
import pandas as pd
import glob
import os
import subprocess
from IPython.display import display, HTML

# Identify the most recent results directory
model_basename = MODEL_PATH.split('/')[-1]
result_dirs = glob.glob(f"{longbench_results_dir}/{model_basename}_*_{LAYER_STEP}_v4")

if not result_dirs:
    print("No results found to evaluate. Please run the execution pipeline above first.")
else:
    # Select the most recently created results directory
    latest_results_dir = max(result_dirs, key=os.path.getmtime)
    print(f"Evaluating results from: {latest_results_dir}")
    
    # Run the evaluation script
    # We call PyramidKV/eval.py which handles calculation across all methods and datasets
    eval_cmd = [
        "python3", "PyramidKV/eval.py",
        "--results_dir", latest_results_dir
    ]
    
    print("Calculating metrics (this may take a minute)...")
    result = subprocess.run(eval_cmd, capture_output=True, text=True)
    
    if result.returncode == 0:
        # Load and display the comparison table
        csv_path = os.path.join(latest_results_dir, "results.csv")
        if os.path.exists(csv_path):
            results_df = pd.read_csv(csv_path)
            print("\n✅ Performance Analysis Complete!")
            display(HTML("<h3>LongBench Performance Comparison</h3>"))
            display(results_df)
        else:
            print(f"Evaluation finished, but {csv_path} was not found. check output below:")
            print(result.stdout)
    else:
        print("❌ Evaluation script failed!")
        print(result.stdout)
        print(result.stderr)

Evaluating results from: ./results_long_bench/Llama-3.2-3B-Instruct_64_1_v4
Calculating metrics (this may take a minute)...
❌ Evaluation script failed!

python3: can't open file '/kaggle/working/CommonKV/PyramidKV/eval.py': [Errno 2] No such file or directory

## 4. RULER Benchmark
You can run an identical loop for RULER using `run_ruler.py` simply by swapping the command in Section 2!

In [31]:
# longbench_results_dir = "./results_ruler"
# os.makedirs(longbench_results_dir, exist_ok=True)
# MODEL_PATH = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

# for method in METHODS_TO_TEST:
#     print(f"\n{'='*50}\nEvaluating Method: {method.upper()}\n{'='*50}")
    
#     # We swap 'commonkv' <-> 'ours' dynamically if user mismatched the model type
#     eval_method = method
#     if 'llama' in MODEL_PATH.lower() and method == 'ours':
#         eval_method = 'commonkv'
#     if 'mistral' in MODEL_PATH.lower() and method == 'commonkv':
#         eval_method = 'ours'

#     # # Build the command for LongBench
#     # cmd = [
#     #     "python3", "run_longbench.py",
#     #     "--method", eval_method,
#     #     "--model_path", MODEL_PATH,
#     #     "--dataset", DATASET,
#     #     "--max_capacity_prompts", str(MAX_CAPACITY_PROMPTS),
#     #     "--attn_implementation", "sdpa",  # Switch to 'eager' if FA2 fails
#     #     "--layer_step", str(LAYER_STEP),
#     #     "--rank", str(RANK),
#     #     "--save_dir", longbench_results_dir,
#     #     "--eval_batch_size", "1"
#     # ]


#     # Build the command for LongBench
#     cmd = [
#         "python3", "run_ruler.py",
#         "--method", eval_method,
#         "--model_path", MODEL_PATH,
#         "--dataset", DATASET,
#         "--max_capacity_prompts", str(MAX_CAPACITY_PROMPTS),
#         "--attn_implementation", "sdpa",
#         "--layer_step", str(LAYER_STEP),
#         "--rank", str(RANK),
#         "--save_dir", longbench_results_dir,
#         "--eval_batch_size", "1",
#         "--steps", "5",  # <--- Add this flag and target number here!
#         "--max_datasets", "2",
#         "--max_prefill_tokens_for_custom_methods", "2048"
#     ]
    
#     start_time = time.time()
    
#     # Run the subprocess
#     try:
#         # We stream output to notebook seamlessly
#         process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
#         for line in process.stdout:
#             print(line, end="")
#         process.wait()
        
#         if process.returncode == 0:
#             print(f"\n✅ Successfully completed {method} in {time.time() - start_time:.1f}s")
#         else:
#             print(f"\n❌ Failed or halted {method} (Return code: {process.returncode})")
            
#     except KeyboardInterrupt:
#         print("\nPipeline halted by user.")
#         process.kill()
#         break

In [32]:
# MODEL_PATH = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

# longbench_results_dir = "./results_long_bench"
# os.makedirs(longbench_results_dir, exist_ok=True)
# METHODS_TO_TEST = ['ThinK']
# for method in METHODS_TO_TEST:
#     print(f"\n{'='*50}\nEvaluating Method: {method.upper()}\n{'='*50}")
    
#     # We swap 'commonkv' <-> 'ours' dynamically if user mismatched the model type
#     eval_method = method.lower()
#     if 'llama' in MODEL_PATH.lower() and method == 'ours':
#         eval_method = 'commonkv'
#     if 'mistral' in MODEL_PATH.lower() and method == 'commonkv':
#         eval_method = 'ours'

#     # Build the command for LongBench
#    # ... (rest of your loop configuration)

#     # Build the command for LongBench
#     cmd = [
#         "python3", "run_longbench.py",
#         "--method", eval_method,
#         "--model_path", MODEL_PATH,
#         "--dataset", DATASET,
#         # "--max_capacity_prompts", "2048",   # <--- This triggers the 4x compression for ThinK
#         "--attn_implementation", "sdpa",
#         "--save_dir", longbench_results_dir,
#         "--eval_batch_size", "1",
#         "--steps", "5",                     # Fast test on 5 samples
#         "--max_datasets", "2",
#     ]
    
    
#     start_time = time.time()
    
#     # Run the subprocess
#     try:
#         # We stream output to notebook seamlessly
#         process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
#         for line in process.stdout:
#             print(line, end="")
#         process.wait()
        
#         if process.returncode == 0:
#             print(f"\n✅ Successfully completed {method} in {time.time() - start_time:.1f}s")
#         else:
#             print(f"\n❌ Failed or halted {method} (Return code: {process.returncode})")
            
#     except KeyboardInterrupt:
#         print("\nPipeline halted by user.")
#         process.kill()
#         break

In [33]:
import torch

torch.cuda.empty_cache()

In [34]:
import torch

torch.cuda.empty_cache()
torch.cuda.ipc_collect()